# Generated by Django 2.1.8 on 2019-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='не более 100 символов, используется для манипуляции с новостью, а также по умолчанию в качестве title, description, header', max_length=300, verbose_name='название новости'),
        ),
    ]
