# Generated by Django 2.1.8 on 2019-04-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190412_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='search_data',
            field=models.CharField(blank=True, max_length=10000, null=True, verbose_name='данные для поиска'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='не более 300 символов, используется для манипуляции с новостью, а также по умолчанию в качестве title, description, header', max_length=300, verbose_name='название новости'),
        ),
    ]
