# Generated by Django 2.1.7 on 2019-06-09 13:22

from django.db import migrations, models
import easy_thumbnails.fields
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190412_2321'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at',), 'verbose_name': 'Вопрос-ответ', 'verbose_name_plural': 'Вопросы-ответы'},
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(blank=True, help_text='не более 500 символов, по умолчанию будут использованы первые ч00 знаков "текста". анонс не выводится на странице с текстом', max_length=500, null=True, verbose_name='анонс'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, help_text='если это поле пустое, то прикрепленное изображение выводится по центру на всю страницу', null=True, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(blank=True, help_text='не более 500 символов, по умолчанию будет использован "анонс", а при его отсутствии - "название"  (если не знаете что это такое - спросите у своего SEO-шника)', max_length=500, null=True, verbose_name='поле description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, help_text='не более 200 символов, по умолчанию будет использовано "заголовок"', max_length=200, null=True, verbose_name='основной заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='размеры изображения на странице -  770x562 (обрезается), в списке - 370x270 (обрезается)', null=True, upload_to=news.models.Post.get_upload_path, verbose_name='Основное изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(help_text='не более 300 символов, используется для манипуляции с новостью, а также по умолчанию в качестве title, description, header', max_length=300, verbose_name='заголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, help_text='не более 300 символов, по умолчанию будет использовано "название" (если не знаете что это такое - спросите у своего SEO-шника)', max_length=300, null=True, verbose_name='поле title'),
        ),
    ]
