# Generated by Django 2.0.2 on 2019-03-25 15:14

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import tinymce.models
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconimg', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='не более 20 символов', null=True, upload_to='', verbose_name='Картинка иконки')),
                ('icon', models.CharField(blank=True, help_text='не более 20 символов', max_length=20, null=True, verbose_name='Иконка')),
                ('title', models.CharField(blank=True, help_text='не более 100 символов', max_length=100, null=True, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, help_text='не более 200 символов', max_length=200, null=True, verbose_name='Текст')),
                ('url', models.CharField(blank=True, help_text='не более 200 символов', max_length=200, null=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуга',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='наименование организации', help_text='наименование организации', max_length=255, verbose_name='наименование организации')),
                ('phone1', models.CharField(help_text='не более 20 символов', max_length=20, verbose_name='номер телефона правления')),
                ('phone2', models.CharField(blank=True, help_text='не более 20 символов', max_length=20, null=True, verbose_name='номер телефона ухгалтерии')),
                ('email', models.EmailField(help_text='не более 60 символов', max_length=60, verbose_name='адрес электронной почты')),
                ('openings', models.CharField(blank=True, help_text='не более 40 символов', max_length=40, null=True, verbose_name='рабочее время')),
                ('openings_full', models.TextField(blank=True, help_text='не более 200 символов, можно использовать HTML тэги', max_length=200, null=True, verbose_name='рабочее время, полностью')),
                ('facebook', models.URLField(blank=True, help_text='не более 120 символов', max_length=120, null=True, verbose_name='facebook')),
                ('vk', models.URLField(blank=True, help_text='не более 120 символов', max_length=120, null=True, verbose_name='вКонтакте')),
                ('instagram', models.URLField(blank=True, help_text='не более 120 символов', max_length=120, null=True, verbose_name='instagram')),
                ('twitter', models.URLField(blank=True, help_text='не более 120 символов', max_length=120, null=True, verbose_name='twitter')),
                ('googleplus', models.URLField(blank=True, help_text='не более 120 символов', max_length=120, null=True, verbose_name='google+')),
                ('youtube', models.URLField(blank=True, help_text='не более 120 символов', max_length=120, null=True, verbose_name='youtube')),
                ('odnoklassniki', models.URLField(blank=True, help_text='не более 120 символов', max_length=120, null=True, verbose_name='одноклассники ')),
                ('address', models.CharField(blank=True, help_text='не более 200 символов', max_length=200, null=True, verbose_name='адрес')),
                ('map', models.TextField(blank=True, help_text='не более 500 символов', max_length=500, null=True, verbose_name='код для вставки карт на сайт')),
                ('slogan', models.TextField(blank=True, help_text='не более 500 символов (рекомендуется 250 и по содержанию близко к SEO-description главной страницы)', max_length=500, null=True, verbose_name='промо-текст в подвал')),
                ('active', models.BooleanField(default=False, verbose_name='активные настройки')),
                ('htext_contacts', tinymce.models.HTMLField(blank=True, null=True, verbose_name='HTML текст на страницу "контакты"')),
                ('htext_about', tinymce.models.HTMLField(blank=True, null=True, verbose_name='HTML текст на страницу "о нас"')),
                ('htext_persdata', tinymce.models.HTMLField(blank=True, null=True, verbose_name='HTML текст на страницу "политика обработки персональных данных"')),
                ('logo', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='соотношение сторон должно быть 300*100', null=True, upload_to=website.models.Contact.get_upload_path, verbose_name='основной логотип')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Landingpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название страницы')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='уникальный адрес страницы')),
                ('title', models.CharField(blank=True, help_text='не более 300 символов, по умолчанию будет использовано "название страницы" (если не знаете что это такое - спросите у своего SEO-шника)', max_length=300, null=True, verbose_name='поле title страницы')),
                ('description', models.CharField(blank=True, help_text='не более 500 символов, по умолчанию будет использовано "название страницы" (если не знаете что это такое - спросите у своего SEO-шника)', max_length=500, null=True, verbose_name='поле description страницы')),
                ('helo_text', models.CharField(blank=True, help_text='не более 50 символов', max_length=50, null=True, verbose_name='приветствие')),
                ('subhelo_text', models.CharField(blank=True, help_text='не более 100 символов', max_length=100, null=True, verbose_name='под приветствие')),
                ('content_text', models.TextField(blank=True, help_text='не более 5000 символов. на странице текст выводится в 2 колонки, разбиваясь на 2 более-менее равные части. Для принудительного разбиения поставьте символ "#" (решетка)', max_length=5000, null=True, verbose_name='Основной текст')),
                ('use_testimonial_section', models.BooleanField(default=True, verbose_name='Секция "Полезные советы"')),
                ('testimonial_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('use_fp_section', models.BooleanField(default=True, verbose_name='Секция "Избранные страницы"')),
                ('fp_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('fp_action_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка URL')),
                ('fp_action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки')),
                ('content_image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=website.models.Landingpage.get_upload_path, verbose_name='Основное изображение')),
                ('use_cta_section', models.BooleanField(default=True, verbose_name='Секция "Призыв к действию"')),
                ('cta_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('cta_text', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст секции призыв к действию')),
                ('cta_action_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка URL')),
                ('cta_action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки')),
                ('use_persons_section', models.BooleanField(default=True, verbose_name='Секция "Персонал"')),
                ('persons_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('use_banners_section', models.BooleanField(default=True, verbose_name='Секция "Баннеры"')),
                ('banners_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('use_userhtml_section', models.BooleanField(default=True, verbose_name='Секция "Пользовательский HTML"')),
                ('userhtml_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('userhtml_text', models.TextField(blank=True, max_length=10000, null=True, verbose_name='Пользовательский HTML')),
                ('use_video_section', models.BooleanField(default=True, verbose_name='Секция "Видео"')),
                ('video_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('video_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Видео 1')),
                ('video_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Видео 2')),
                ('use_news_section', models.BooleanField(default=True, verbose_name='Секция "Новости"')),
                ('news_header', models.CharField(blank=True, max_length=100, null=True, verbose_name='Заголовок секции')),
                ('news_action_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='ссылка URL')),
                ('news_action_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст кнопки')),
            ],
            options={
                'verbose_name': 'Посадочная страница',
                'verbose_name_plural': 'Посадочные страницы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SS', 'Простой слайд'), ('SB', 'Слайд с баннером')], default='SS', max_length=2)),
                ('background', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=website.models.Slide.get_upload_path, verbose_name='Фон слайда')),
                ('name', models.CharField(max_length=100, verbose_name='название слайда')),
                ('header', models.CharField(blank=True, max_length=100, null=True, verbose_name='заголовок баннера')),
                ('text1', models.CharField(blank=True, max_length=100, null=True, verbose_name='текст 1-я строка баннера')),
                ('text2', models.CharField(blank=True, max_length=100, null=True, verbose_name='текст 2-я строка баннера')),
                ('text3', models.CharField(blank=True, max_length=100, null=True, verbose_name='текст 3-я строка баннера')),
                ('action_url', models.CharField(blank=True, help_text='URL кнопки, телефона (в зависимости от макета)', max_length=200, null=True, verbose_name='URL действия')),
                ('action_text', models.CharField(blank=True, help_text='текст кнопки, телефона (в зависимости от макета)', max_length=100, null=True, verbose_name='текст действия')),
            ],
            options={
                'verbose_name': 'Слайд',
                'verbose_name_plural': 'Слайды',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='не более 30 символов', max_length=30, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, help_text='не более 500 символов', max_length=500, null=True, verbose_name='Текст')),
                ('frontpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='testimonials', to='website.Landingpage', verbose_name='посадочная страница')),
            ],
            options={
                'verbose_name': 'Совет',
                'verbose_name_plural': 'Советы',
            },
        ),
        migrations.AddField(
            model_name='landingpage',
            name='slides',
            field=models.ManyToManyField(blank=True, related_name='pages', to='website.Slide', verbose_name='слайды'),
        ),
        migrations.AddField(
            model_name='contact',
            name='frontpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='website.Landingpage', verbose_name='Лендинг'),
        ),
        migrations.AddField(
            model_name='contact',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.GalleryCategory', verbose_name='Фотографии на главной'),
        ),
        migrations.AddField(
            model_name='contact',
            name='main_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.MenuItem', verbose_name='Основное меню'),
        ),
        migrations.AddField(
            model_name='advantage',
            name='frontpage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advantages', to='website.Landingpage', verbose_name='посадочная страница'),
        ),
    ]
