# Generated by Django 2.1.8 on 2019-05-23 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textonmain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='не более 30 символов', max_length=30, null=True, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, help_text='не более 5000 символов, допустимы символы HTML', max_length=5000, null=True, verbose_name='Текст')),
                ('frontpage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='textonmain', to='website.Landingpage', verbose_name='посадочная страница')),
            ],
            options={
                'verbose_name': 'Текст на главной',
                'verbose_name_plural': 'Тексты на главной',
            },
        ),
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='SHIT001',
        ),
    ]
