# Generated by Django 2.1.7 on 2019-05-27 13:59

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190527_1659'),
        ('website', '0002_auto_20190523_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='menu_articles',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_articles', to='menu.MenuItem', verbose_name='Меню статьи'),
        ),
        migrations.AddField(
            model_name='contact',
            name='menu_countries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_countries', to='menu.MenuItem', verbose_name='Меню страны'),
        ),
        migrations.AddField(
            model_name='contact',
            name='menu_services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_services', to='menu.MenuItem', verbose_name='Меню услуги'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='соотношение сторон должно быть 315*46', null=True, upload_to=website.models.Contact.get_upload_path, verbose_name='основной логотип'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='main_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_menu', to='menu.MenuItem', verbose_name='Основное меню (разделы)'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone1',
            field=models.CharField(help_text='не более 20 символов', max_length=20, verbose_name='номер телефона СПб'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone2',
            field=models.CharField(blank=True, help_text='не более 20 символов', max_length=20, null=True, verbose_name='номер телефона Москва'),
        ),
    ]
