# Generated by Django 2.0.2 on 2019-03-31 15:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('QUESTION', 'Вопрос с сайта'), ('NOTIFICATION', 'Уведомление'), ('DOC_REQUEST', 'Запрос документов'), ('CALC_REQUEST', 'Запрос расчета'), ('CALL_REQUEST', 'Запрос звонка'), ('USER_MESSAGE', 'Ответ пользователя'), ('SYS_MESSAGE', 'Ответ системы')], default='QUESTION', max_length=16, verbose_name='Тип сообщения')),
                ('phone', models.CharField(blank=True, help_text='ваш контактный номер, не более 20 символов', max_length=20, null=True, verbose_name='телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SEND', 'Отправлено'), ('READ', 'Прочитано'), ('FLAG', 'Важное'), ('DELETED', 'Удалено')], default='DRAFT', max_length=10, verbose_name='Статус сообщения')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время отправки')),
                ('title', models.CharField(blank=True, help_text='не более 200 символов', max_length=200, null=True, verbose_name='Заголовок сообщения')),
                ('text', models.TextField(blank=True, help_text='не более 50000 символов', max_length=50000, null=True, verbose_name='Текст сообщения')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('-created_at',),
            },
        ),
    ]
