# Generated by Django 2.0.2 on 2019-03-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymessages', '0002_auto_20190331_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(blank=True, help_text='не более 100 символов', max_length=100, null=True, verbose_name='Имя отправителя'),
        ),
    ]
