# Generated by Django 2.0.2 on 2019-03-25 15:14

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import mptt.fields
import pages.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='не более 500 символов', max_length=500, verbose_name='название документа')),
                ('file', models.FileField(upload_to=pages.models.Document._get_upload_path, verbose_name='файл документа')),
                ('uploaded', models.DateField(default=datetime.date.today, verbose_name='загружен')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('name', models.CharField(help_text='не более 100 символов, используется для манипуляции со страницей, а также по умолчанию в качестве title, description, header', max_length=100, verbose_name='название страницы')),
                ('title', models.CharField(blank=True, help_text='не более 300 символов, по умолчанию будет использовано "название страницы" (если не знаете что это такое - спросите у своего SEO-шника)', max_length=300, null=True, verbose_name='поле title страницы')),
                ('description', models.CharField(blank=True, help_text='не более 500 символов, по умолчанию будет использовано "название страницы" (если не знаете что это такое - спросите у своего SEO-шника)', max_length=500, null=True, verbose_name='поле description страницы')),
                ('anchor_short', models.CharField(blank=True, help_text='текст ссылки длиной до 30 символов, данная текст используется там где место ограничено (в меню и т.д.)', max_length=30, null=True, verbose_name='коороткая ссылка')),
                ('anchor_full', models.CharField(blank=True, help_text='текст ссылки длиной до 150 символов', max_length=150, null=True, verbose_name='длинная ссылка')),
                ('header', models.CharField(blank=True, help_text='не более 200 символов, по умолчанию будет использовано "название страницы"', max_length=200, null=True, verbose_name='основной заголовок страницы')),
                ('subheader', models.CharField(blank=True, help_text='не более 200 символов', max_length=200, null=True, verbose_name='подзаголовок страницы')),
                ('promotext', models.TextField(blank=True, help_text='не более 1000 символов', max_length=1000, null=True, verbose_name='промо текст в верхнюю часть страницы')),
                ('safetext', models.TextField(blank=True, help_text='не более 50000 символов', max_length=50000, null=True, verbose_name='html текст в верхнюю часть страницы (под промотекст). Сюда вставляются коды JS для карт или прочего')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содержимое страницы')),
                ('show_childs', models.BooleanField(default=False, help_text='после основного содержимого можно вывести список страниц раздела. Страницы выводятся "плашками".', verbose_name='Отображать список дочерних страниц')),
                ('hide_in_parent_list', models.BooleanField(default=False, help_text='Этот пункт надо отметить, что бы не выводить ссылку на эту стараницу в списке дочерних страниц у родительской страницы.', verbose_name='Не показывать в списке родительской страницы')),
                ('show_frontimage', models.BooleanField(default=False, verbose_name='Отображать крупное изображение в начале страницы')),
                ('embed_documents', models.BooleanField(default=False, verbose_name='Встраивать прикрепленные документы в текст страницы')),
                ('favorite_page', models.BooleanField(default=False, help_text='Избранная страница, для отображения на главной', verbose_name='Избранная')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='размеры изображения на странице -  1170x550 (обрезается), в списке страниц или новостей - 348x220 (обрезается)', null=True, upload_to=pages.models.Page._get_upload_path, verbose_name='Основное изображение страницы')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('attached_gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallery.GalleryCategory', verbose_name='галерея')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.Page', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docs', to='pages.Page', verbose_name='Страница'),
        ),
    ]
