# Generated by Django 2.1.8 on 2019-04-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190412_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='canonical_tail',
            field=models.CharField(choices=[('/', '/'), ('.php', '.php'), ('.html', '.html')], default='/', max_length=5, verbose_name='окончание канонического ЧПУ'),
        ),
    ]
