# Generated by Django 2.1.8 on 2019-04-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190412_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='canonical_tail',
            field=models.CharField(choices=[('/', '/'), ('.php', '.php'), ('.html', '.html'), ('/index.html', '/index.html'), ('/index.php', '/index.php')], default='/', max_length=5, verbose_name='окончание канонического ЧПУ'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=84, unique=True, verbose_name='относительный ЧПУ'),
        ),
    ]
