# Generated by Django 2.1.8 on 2019-04-12 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20190412_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(max_length=84, verbose_name='относительный ЧПУ'),
        ),
    ]
