# Generated by Django 2.1.8 on 2019-04-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190412_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(help_text='не более 100 символов, используется для манипуляции со страницей, а также по умолчанию в качестве title, description, header', max_length=300, verbose_name='название страницы'),
        ),
    ]
