# Generated by Django 2.0.2 on 2019-03-25 15:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.query_utils
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование страницы')),
                ('link', models.CharField(blank=True, max_length=128, null=True, verbose_name='адрес страницы')),
            ],
            options={
                'verbose_name': 'Фиксированная страница',
                'verbose_name_plural': 'Фиксированные страницы',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='текст в меню')),
                ('link', models.CharField(blank=True, max_length=128, null=True, verbose_name='произвольная ссылка')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('content_type', models.ForeignKey(blank=True, limit_choices_to=django.db.models.query_utils.Q(django.db.models.query_utils.Q(('app_label', 'menu'), ('model', 'FixedPage'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'pages'), ('model', 'Page'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'staff'), ('model', 'Person'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'gallery'), ('model', 'GalleryCategory'), _connector='AND'), django.db.models.query_utils.Q(('app_label', 'news'), ('model', 'PostCategory'), _connector='AND'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='тип содержимого')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='menu.MenuItem', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
    ]
