# Generated by Django 2.1.8 on 2019-05-16 13:33

from django.db import migrations, models
import easy_thumbnails.fields
import testimonials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='не более 30 символов', max_length=30, null=True, verbose_name='Имя')),
                ('text', models.TextField(blank=True, help_text='не более 5000 символов', max_length=5000, null=True, verbose_name='Текст')),
                ('moderated', models.BooleanField(default=False, verbose_name='Отзыв проверен')),
                ('created_at', models.DateField(blank=True, null=True, verbose_name='Дата отзыва')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=testimonials.models.Testimonial.get_upload_path, verbose_name='Фотография для отзыва')),
                ('scan', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=testimonials.models.Testimonial.get_upload_path, verbose_name='Скан отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
