# Generated by Django 2.1.8 on 2019-05-23 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='name',
            field=models.CharField(blank=True, help_text='не более 100 символов', max_length=100, null=True, verbose_name='Имя'),
        ),
    ]
