# Generated by Django 2.1.7 on 2019-05-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0002_auto_20190516_1639'),
        ('testimonials', '0002_auto_20190523_2056'),
    ]

    operations = [
    ]
