# Generated by Django 2.0.2 on 2019-03-25 15:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
                ('title', models.CharField(db_index=True, help_text='не более 500 символов', max_length=500, verbose_name='Наименование груза')),
            ],
        ),
        migrations.CreateModel(
            name='CargoStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания статуса')),
                ('status', models.CharField(choices=[('PREPARE', 'Забирается перевозчиком'), ('GOT', 'Получен перевозчиком'), ('TRANSPORT', 'Находится в пути в стран назначения'), ('ARRIVED', 'Прибыл в страну назначения'), ('CUSTOMS', 'Ожидает таможенной очистки'), ('READY', 'Готов к получению')], default='PREPARE', max_length=10)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_statuses', to='orders.Cargo', verbose_name='Груз')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='не более 100 символов', max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now, verbose_name='Время создания')),
                ('addressFrom', models.CharField(blank=True, help_text='не более 300 символов', max_length=300, null=True, verbose_name='Точка отправления')),
                ('addressTo', models.CharField(blank=True, help_text='не более 300 символов', max_length=300, null=True, verbose_name='Точка получения')),
                ('description', models.TextField(blank=True, help_text='не более 20000 символов', max_length=20000, null=True, verbose_name='Заголовок сообщения')),
                ('weight', models.IntegerField(blank=True, help_text='вес груза в килограммах', null=True, verbose_name='Вес')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='объем груза в метрах кубических', max_digits=10, null=True, verbose_name='Объем')),
                ('value', models.IntegerField(blank=True, help_text='стоимость груза в долларах', null=True, verbose_name='Стоимость груза')),
                ('customs_needed', models.BooleanField(help_text='требуются услуги по растамаживанию груза', verbose_name='Требуется растаможка')),
                ('price', models.IntegerField(blank=True, help_text='стоимость перевозки в долларах', null=True, verbose_name='Стоимость перевозки')),
                ('price_include_customs', models.BooleanField(help_text='стоимость включает услуги по растамаживанию груза', verbose_name='Растаможка')),
                ('countryFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_messages', to='orders.Country', verbose_name='Страна отправки')),
                ('countryTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='orders.Country', verbose_name='Страна доставки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-pk',),
            },
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='не более 100 символов', max_length=100, verbose_name='Наименование')),
                ('percent', models.IntegerField(db_index=True, help_text='целое количество %', verbose_name='Таможенный тариф')),
            ],
            options={
                'verbose_name': 'Тип груза',
                'verbose_name_plural': 'Типы груза',
                'ordering': ('title',),
            },
        ),
    ]
