# Generated by Django 2.0.2 on 2019-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20190329_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ('title',), 'verbose_name': 'Вид груза', 'verbose_name_plural': 'Виды груза'},
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='не более 20000 символов', max_length=20000, null=True, verbose_name='Описание груза, дополнительные требования и пожелания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_include_customs',
            field=models.BooleanField(default=False, help_text='стоимость включает услуги по растамаживанию груза', verbose_name='Растаможка'),
        ),
    ]
