# Generated by Django 2.0.2 on 2019-03-31 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20190331_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='не более 100 символов', max_length=100, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Перевозчик',
                'verbose_name_plural': 'Перевозчики',
                'ordering': ('title',),
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='tk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargos', to='orders.Tk', verbose_name='Перевозчик'),
        ),
    ]
