# Generated by Django 2.0.2 on 2019-03-31 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190331_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargostatus',
            options={'ordering': ('-pk',), 'verbose_name': 'Статус груза', 'verbose_name_plural': 'Статус груза'},
        ),
    ]
