# Generated by Django 2.1.8 on 2019-04-12 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20190412_1117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_a_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена авиа/кг')),
                ('price_a_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена авиа/м куб.')),
                ('price_s_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена море/кг')),
                ('price_s_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена море/м куб.')),
            ],
        ),
        migrations.AddField(
            model_name='country',
            name='b_from',
            field=models.BooleanField(default=1, help_text='Точка отправления груза', verbose_name='Откуда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='b_to',
            field=models.BooleanField(default=1, help_text='Точка назначения груза', verbose_name='Куда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='c_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='f_prices', to='orders.Country', verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='price',
            name='c_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_prices', to='orders.Country', verbose_name='Куда'),
        ),
    ]
