# Generated by Django 2.1.8 on 2019-04-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190412_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='days_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок перевозки авиа'),
        ),
        migrations.AddField(
            model_name='price',
            name='days_s',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок перевозки морем'),
        ),
    ]
