# Generated by Django 2.1.8 on 2019-04-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20190413_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trby',
            field=models.CharField(choices=[('AIR', 'Авиа перевозка'), ('SEA', 'Морская перевозка'), ('AUTO', 'Морская перевозка'), ('TRIAN', 'Ж/Д перевозка'), ('HORSE', 'Перевозка гужевым транспортом'), ('OTHER', 'Прочая перевозка')], default='AIR', max_length=6, verbose_name='Тип перевозки'),
        ),
    ]
