# Generated by Django 2.1.7 on 2019-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20190516_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price_a_kg0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена авиа (минимальная)'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_a_kg1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг авиа от 100 кг'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_a_kg3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг авиа от 300 кг'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_a_kg5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг авиа от 500 кг'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_s_kg0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена море (минимальная)'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_s_kg1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг море от 100 кг'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_s_kg3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг море от 300 кг'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_s_kg5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг море от 500 кг'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_a_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг  авиа от 1000 кг'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_a_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ценам куб авиа'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_s_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/кг море от 1000 кг'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_s_m3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Цена/м куб. море'),
        ),
    ]
