# Generated by Django 2.1.7 on 2019-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20190530_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Наименование груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='addressFrom',
            field=models.CharField(blank=True, help_text='указывается по необходимости, не более 300 символов', max_length=300, null=True, verbose_name='Адрес забора груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='addressTo',
            field=models.CharField(blank=True, help_text='указывается по необходимости, не более 300 символов', max_length=300, null=True, verbose_name='Адрес доставки груза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='trby',
            field=models.CharField(choices=[('AIR', 'Авиа перевозка'), ('SEA', 'Морская перевозка'), ('AUTO', 'Авто перевозка'), ('TRIAN', 'Ж/Д перевозка'), ('HORSE', 'Мультимодальная перевозка'), ('OTHER', 'Прочая перевозка')], default='AIR', max_length=6, verbose_name='Тип перевозки'),
        ),
    ]
